with tb_match_player as (
  select 
         match_id,
         from_unixtime(activate_time) as dt_match_start,
         from_unixtime(last_update_time) as dt_match_update,
         team_id_radiant,
         team_id_dire,
         explode(players) as player
  from live_games

),

tb_join_all (

  select t1.match_id,
         t1.dt_match_start,
         date(t1.dt_match_start) as dt_match,
         t1.dt_match_update,
         t1.player.team_id,
         t1.team_id_radiant,
         t1.team_id_dire,
         case when t1.player.team_id = t1.team_id_radiant then 1 else 0 end as isRadiant,
         t2.*

  from tb_match_player as t1

  left join silver_gamelakehouse.fs_dota_player_matches as t2
  on t1.player.account_id = t2.account_id
  and date(t1.dt_match_start) = t2.dtReference

  where team_id_dire > 0 and team_id_radiant > 0

),

tb_summary(

  select match_id,
         dt_match_start,
         dt_match_update,
         team_id_radiant,
         team_id_dire,
        coalesce(min(case when isRadiant = 1 then qtMatches end),-1) as minqtMatchesRadiant,
        coalesce(avg(case when isRadiant = 1 then qtMatches end),-1) as qtMatchesRadiant,
        coalesce(max(case when isRadiant = 1 then qtMatches end),-1) as maxqtMatchesRadiant,
        coalesce(min(case when isRadiant = 1 then qtMatchMonth end),-1) as minqtMatchMonthRadiant,
        coalesce(avg(case when isRadiant = 1 then qtMatchMonth end),-1) as qtMatchMonthRadiant,
        coalesce(max(case when isRadiant = 1 then qtMatchMonth end),-1) as maxqtMatchMonthRadiant,
        coalesce(min(case when isRadiant = 1 then qtMatchMonth6 end),-1) as minqtMatchMonth6Radiant,
        coalesce(avg(case when isRadiant = 1 then qtMatchMonth6 end),-1) as qtMatchMonth6Radiant,
        coalesce(max(case when isRadiant = 1 then qtMatchMonth6 end),-1) as maxqtMatchMonth6Radiant,
        coalesce(min(case when isRadiant = 1 then qtHeros end),-1) as minqtHerosRadiant,
        coalesce(avg(case when isRadiant = 1 then qtHeros end),-1) as qtHerosRadiant,
        coalesce(max(case when isRadiant = 1 then qtHeros end),-1) as maxqtHerosRadiant,
        coalesce(min(case when isRadiant = 1 then qtDaysLastMatch end),-1) as minqtDaysLastMatchRadiant,
        coalesce(avg(case when isRadiant = 1 then qtDaysLastMatch end),-1) as qtDaysLastMatchRadiant,
        coalesce(max(case when isRadiant = 1 then qtDaysLastMatch end),-1) as maxqtDaysLastMatchRadiant,
        coalesce(min(case when isRadiant = 1 then qtDaysFirstMatch end),-1) as minqtDaysFirstMatchRadiant,
        coalesce(avg(case when isRadiant = 1 then qtDaysFirstMatch end),-1) as qtDaysFirstMatchRadiant,
        coalesce(max(case when isRadiant = 1 then qtDaysFirstMatch end),-1) as maxqtDaysFirstMatchRadiant,
        coalesce(min(case when isRadiant = 1 then avgWinRate end),-1) as minavgWinRateRadiant,
        coalesce(avg(case when isRadiant = 1 then avgWinRate end),-1) as avgWinRateRadiant,
        coalesce(max(case when isRadiant = 1 then avgWinRate end),-1) as maxavgWinRateRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgKillMinute end),-1) as minvlAvgKillMinuteRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgKillMinute end),-1) as vlAvgKillMinuteRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgKillMinute end),-1) as maxvlAvgKillMinuteRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgAssists end),-1) as minvlAvgAssistsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgAssists end),-1) as vlAvgAssistsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgAssists end),-1) as maxvlAvgAssistsRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgCampsStacked end),-1) as minvlAvgCampsStackedRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgCampsStacked end),-1) as vlAvgCampsStackedRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgCampsStacked end),-1) as maxvlAvgCampsStackedRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgCreepsStacked end),-1) as minvlAvgCreepsStackedRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgCreepsStacked end),-1) as vlAvgCreepsStackedRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgCreepsStacked end),-1) as maxvlAvgCreepsStackedRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgDeaths end),-1) as minvlAvgDeathsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgDeaths end),-1) as vlAvgDeathsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgDeaths end),-1) as maxvlAvgDeathsRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgDenies end),-1) as minvlAvgDeniesRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgDenies end),-1) as vlAvgDeniesRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgDenies end),-1) as maxvlAvgDeniesRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgFirstblood end),-1) as minvlAvgFirstbloodRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgFirstblood end),-1) as vlAvgFirstbloodRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgFirstblood end),-1) as maxvlAvgFirstbloodRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgGoldMinute end),-1) as minvlAvgGoldMinuteRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgGoldMinute end),-1) as vlAvgGoldMinuteRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgGoldMinute end),-1) as maxvlAvgGoldMinuteRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgKills end),-1) as minvlAvgKillsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgKills end),-1) as vlAvgKillsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgKills end),-1) as maxvlAvgKillsRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgRune end),-1) as minvlAvgRuneRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgRune end),-1) as vlAvgRuneRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgRune end),-1) as maxvlAvgRuneRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgXpMinute end),-1) as minvlAvgXpMinuteRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgXpMinute end),-1) as vlAvgXpMinuteRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgXpMinute end),-1) as maxvlAvgXpMinuteRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgKDA end),-1) as minvlAvgKDARadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgKDA end),-1) as vlAvgKDARadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgKDA end),-1) as maxvlAvgKDARadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgNeutralKills end),-1) as minvlAvgNeutralKillsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgNeutralKills end),-1) as vlAvgNeutralKillsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgNeutralKills end),-1) as maxvlAvgNeutralKillsRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgObserverKills end),-1) as minvlAvgObserverKillsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgObserverKills end),-1) as vlAvgObserverKillsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgObserverKills end),-1) as maxvlAvgObserverKillsRadiant,
        coalesce(min(case when isRadiant = 1 then vlAvgSentryKills end),-1) as minvlAvgSentryKillsRadiant,
        coalesce(avg(case when isRadiant = 1 then vlAvgSentryKills end),-1) as vlAvgSentryKillsRadiant,
        coalesce(max(case when isRadiant = 1 then vlAvgSentryKills end),-1) as maxvlAvgSentryKillsRadiant,
        coalesce(min(case when isRadiant = 1 then pctLaneRole1 end),-1) as minpctLaneRole1Radiant,
        coalesce(avg(case when isRadiant = 1 then pctLaneRole1 end),-1) as pctLaneRole1Radiant,
        coalesce(max(case when isRadiant = 1 then pctLaneRole1 end),-1) as maxpctLaneRole1Radiant,
        coalesce(min(case when isRadiant = 1 then pctLaneRole2 end),-1) as minpctLaneRole2Radiant,
        coalesce(avg(case when isRadiant = 1 then pctLaneRole2 end),-1) as pctLaneRole2Radiant,
        coalesce(max(case when isRadiant = 1 then pctLaneRole2 end),-1) as maxpctLaneRole2Radiant,
        coalesce(min(case when isRadiant = 1 then pctLaneRole3 end),-1) as minpctLaneRole3Radiant,
        coalesce(avg(case when isRadiant = 1 then pctLaneRole3 end),-1) as pctLaneRole3Radiant,
        coalesce(max(case when isRadiant = 1 then pctLaneRole3 end),-1) as maxpctLaneRole3Radiant,
        coalesce(min(case when isRadiant = 1 then pctLaneRole4 end),-1) as minpctLaneRole4Radiant,
        coalesce(avg(case when isRadiant = 1 then pctLaneRole4 end),-1) as pctLaneRole4Radiant,
        coalesce(max(case when isRadiant = 1 then pctLaneRole4 end),-1) as maxpctLaneRole4Radiant,

        coalesce(min(case when isRadiant = 0 then qtMatches end),-1) as minqtMatchesDire,
        coalesce(avg(case when isRadiant = 0 then qtMatches end),-1) as qtMatchesDire,
        coalesce(max(case when isRadiant = 0 then qtMatches end),-1) as maxqtMatchesDire,
        coalesce(min(case when isRadiant = 0 then qtMatchMonth end),-1) as minqtMatchMonthDire,
        coalesce(avg(case when isRadiant = 0 then qtMatchMonth end),-1) as qtMatchMonthDire,
        coalesce(max(case when isRadiant = 0 then qtMatchMonth end),-1) as maxqtMatchMonthDire,
        coalesce(min(case when isRadiant = 0 then qtMatchMonth6 end),-1) as minqtMatchMonth6Dire,
        coalesce(avg(case when isRadiant = 0 then qtMatchMonth6 end),-1) as qtMatchMonth6Dire,
        coalesce(max(case when isRadiant = 0 then qtMatchMonth6 end),-1) as maxqtMatchMonth6Dire,
        coalesce(min(case when isRadiant = 0 then qtHeros end),-1) as minqtHerosDire,
        coalesce(avg(case when isRadiant = 0 then qtHeros end),-1) as qtHerosDire,
        coalesce(max(case when isRadiant = 0 then qtHeros end),-1) as maxqtHerosDire,
        coalesce(min(case when isRadiant = 0 then qtDaysLastMatch end),-1) as minqtDaysLastMatchDire,
        coalesce(avg(case when isRadiant = 0 then qtDaysLastMatch end),-1) as qtDaysLastMatchDire,
        coalesce(max(case when isRadiant = 0 then qtDaysLastMatch end),-1) as maxqtDaysLastMatchDire,
        coalesce(min(case when isRadiant = 0 then qtDaysFirstMatch end),-1) as minqtDaysFirstMatchDire,
        coalesce(avg(case when isRadiant = 0 then qtDaysFirstMatch end),-1) as qtDaysFirstMatchDire,
        coalesce(max(case when isRadiant = 0 then qtDaysFirstMatch end),-1) as maxqtDaysFirstMatchDire,
        coalesce(min(case when isRadiant = 0 then avgWinRate end),-1) as minavgWinRateDire,
        coalesce(avg(case when isRadiant = 0 then avgWinRate end),-1) as avgWinRateDire,
        coalesce(max(case when isRadiant = 0 then avgWinRate end),-1) as maxavgWinRateDire,
        coalesce(min(case when isRadiant = 0 then vlAvgKillMinute end),-1) as minvlAvgKillMinuteDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgKillMinute end),-1) as vlAvgKillMinuteDire,
        coalesce(max(case when isRadiant = 0 then vlAvgKillMinute end),-1) as maxvlAvgKillMinuteDire,
        coalesce(min(case when isRadiant = 0 then vlAvgAssists end),-1) as minvlAvgAssistsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgAssists end),-1) as vlAvgAssistsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgAssists end),-1) as maxvlAvgAssistsDire,
        coalesce(min(case when isRadiant = 0 then vlAvgCampsStacked end),-1) as minvlAvgCampsStackedDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgCampsStacked end),-1) as vlAvgCampsStackedDire,
        coalesce(max(case when isRadiant = 0 then vlAvgCampsStacked end),-1) as maxvlAvgCampsStackedDire,
        coalesce(min(case when isRadiant = 0 then vlAvgCreepsStacked end),-1) as minvlAvgCreepsStackedDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgCreepsStacked end),-1) as vlAvgCreepsStackedDire,
        coalesce(max(case when isRadiant = 0 then vlAvgCreepsStacked end),-1) as maxvlAvgCreepsStackedDire,
        coalesce(min(case when isRadiant = 0 then vlAvgDeaths end),-1) as minvlAvgDeathsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgDeaths end),-1) as vlAvgDeathsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgDeaths end),-1) as maxvlAvgDeathsDire,
        coalesce(min(case when isRadiant = 0 then vlAvgDenies end),-1) as minvlAvgDeniesDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgDenies end),-1) as vlAvgDeniesDire,
        coalesce(max(case when isRadiant = 0 then vlAvgDenies end),-1) as maxvlAvgDeniesDire,
        coalesce(min(case when isRadiant = 0 then vlAvgFirstblood end),-1) as minvlAvgFirstbloodDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgFirstblood end),-1) as vlAvgFirstbloodDire,
        coalesce(max(case when isRadiant = 0 then vlAvgFirstblood end),-1) as maxvlAvgFirstbloodDire,
        coalesce(min(case when isRadiant = 0 then vlAvgGoldMinute end),-1) as minvlAvgGoldMinuteDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgGoldMinute end),-1) as vlAvgGoldMinuteDire,
        coalesce(max(case when isRadiant = 0 then vlAvgGoldMinute end),-1) as maxvlAvgGoldMinuteDire,
        coalesce(min(case when isRadiant = 0 then vlAvgKills end),-1) as minvlAvgKillsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgKills end),-1) as vlAvgKillsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgKills end),-1) as maxvlAvgKillsDire,
        coalesce(min(case when isRadiant = 0 then vlAvgRune end),-1) as minvlAvgRuneDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgRune end),-1) as vlAvgRuneDire,
        coalesce(max(case when isRadiant = 0 then vlAvgRune end),-1) as maxvlAvgRuneDire,
        coalesce(min(case when isRadiant = 0 then vlAvgXpMinute end),-1) as minvlAvgXpMinuteDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgXpMinute end),-1) as vlAvgXpMinuteDire,
        coalesce(max(case when isRadiant = 0 then vlAvgXpMinute end),-1) as maxvlAvgXpMinuteDire,
        coalesce(min(case when isRadiant = 0 then vlAvgKDA end),-1) as minvlAvgKDADire,
        coalesce(avg(case when isRadiant = 0 then vlAvgKDA end),-1) as vlAvgKDADire,
        coalesce(max(case when isRadiant = 0 then vlAvgKDA end),-1) as maxvlAvgKDADire,
        coalesce(min(case when isRadiant = 0 then vlAvgNeutralKills end),-1) as minvlAvgNeutralKillsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgNeutralKills end),-1) as vlAvgNeutralKillsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgNeutralKills end),-1) as maxvlAvgNeutralKillsDire,
        coalesce(min(case when isRadiant = 0 then vlAvgObserverKills end),-1) as minvlAvgObserverKillsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgObserverKills end),-1) as vlAvgObserverKillsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgObserverKills end),-1) as maxvlAvgObserverKillsDire,
        coalesce(min(case when isRadiant = 0 then vlAvgSentryKills end),-1) as minvlAvgSentryKillsDire,
        coalesce(avg(case when isRadiant = 0 then vlAvgSentryKills end),-1) as vlAvgSentryKillsDire,
        coalesce(max(case when isRadiant = 0 then vlAvgSentryKills end),-1) as maxvlAvgSentryKillsDire,
        coalesce(min(case when isRadiant = 0 then pctLaneRole1 end),-1) as minpctLaneRole1Dire,
        coalesce(avg(case when isRadiant = 0 then pctLaneRole1 end),-1) as pctLaneRole1Dire,
        coalesce(max(case when isRadiant = 0 then pctLaneRole1 end),-1) as maxpctLaneRole1Dire,
        coalesce(min(case when isRadiant = 0 then pctLaneRole2 end),-1) as minpctLaneRole2Dire,
        coalesce(avg(case when isRadiant = 0 then pctLaneRole2 end),-1) as pctLaneRole2Dire,
        coalesce(max(case when isRadiant = 0 then pctLaneRole2 end),-1) as maxpctLaneRole2Dire,
        coalesce(min(case when isRadiant = 0 then pctLaneRole3 end),-1) as minpctLaneRole3Dire,
        coalesce(avg(case when isRadiant = 0 then pctLaneRole3 end),-1) as pctLaneRole3Dire,
        coalesce(max(case when isRadiant = 0 then pctLaneRole3 end),-1) as maxpctLaneRole3Dire,
        coalesce(min(case when isRadiant = 0 then pctLaneRole4 end),-1) as minpctLaneRole4Dire,
        coalesce(avg(case when isRadiant = 0 then pctLaneRole4 end),-1) as pctLaneRole4Dire,
        coalesce(max(case when isRadiant = 0 then pctLaneRole4 end),-1) as maxpctLaneRole4Dire

  from tb_join_all

  group by match_id, dt_match_start, dt_match_update, team_id_radiant, team_id_dire
)

select * from tb_summary