SELECT '{date}' AS dtReference,
       account_id,
       hero_id,
       MIN(DATEDIFF('{date}', dt_match)) AS qtRecencyHero,
       COUNT(DISTINCT match_id) AS qtMatchesHero,
       AVG(assists) AS avgAssistsHero,
       AVG(camps_stacked) AS avgCampsStackedHero,
       AVG(creeps_stacked) AS avgCreepsStackedHero,
       AVG(deaths) AS avgDeathsHero,
       AVG(denies) AS avgDeniesHero,
       AVG(firstblood_claimed) AS avgFirstbloodClaimedHero,
       AVG(gold) AS avgGoldHero,
       AVG(gold_per_min) AS avgGoldPerMinHero,
       AVG(gold_spent) AS avgGoldSpentHero,
       AVG(hero_damage) AS avgHeroDamageHero,
       AVG(hero_healing) AS avgHeroHealingHero,
       AVG(kills) AS avgKillsHero,
       AVG(last_hits) AS avgLastHitsHero,
       AVG(level) AS avgLevelHero,
       AVG(net_worth) AS avgNetWorthHero,
       AVG(roshans_killed) AS avgRoshansKilledHero,
       AVG(rune_pickups) AS avgRunePickupsHero,
       AVG(xp_per_min) AS avgXpPerMinHero,
       AVG(win) AS avgWinHero,
       AVG(total_gold) AS avgTotalGoldHero,
       AVG(total_xp) AS avgTotalXpHero,
       AVG(kills_per_min) AS avgKillsPerMinHero,
       AVG(kda) AS avgKdaHero,
       AVG(neutral_kills) AS avgNeutralKillsHero,
       AVG(tower_kills) AS avgTowerKillsHero,
       AVG(courier_kills) AS avgCourierKillsHero,
       AVG(lane_kills) AS avgLaneKillsHero,
       AVG(hero_kills) AS avgHeroKillsHero,
       AVG(observer_kills) AS avgObserverKillsHero,
       AVG(sentry_kills) AS avgSentryKillsHero,
       AVG(roshan_kills) AS avgRoshanKillsHero,
       AVG(necronomicon_kills) AS avgNecronomiconKillsHero,
       AVG(ancient_kills) AS avgAncientKillsHero,
       AVG(buyback_count) AS avgBuybackCountHero,
       AVG(observer_uses) AS avgObserverUsesHero,
       AVG(sentry_uses) AS avgSentryUsesHero,
       AVG(lane_efficiency) AS avgLaneEfficiencyHero

FROM bronze.dota.match_players
WHERE dt_match < '{date}'
AND dt_match >= date_add('{date}', -{lag}) 
GROUP BY 1,2,3
ORDER BY 1,2,3